Parser
bmstu-iu9/tiny-refal pull request #10
Opened 2022-09-17 07:41 UTC by MiNombreEsPetros

Need changes, it does not work correctly

2022-09-17 13:12 UTC, Mazdaywik requested changes
Неплохо, но есть несколько ошибок.

2022-09-17 13:12 UTC, Mazdaywik commented on js/javascript.js
> +                  string.replaceAll('()', '');}
У этой строчки отступ поехал, поправьте, пожалуйста.

2022-09-17 13:12 UTC, Mazdaywik commented on js/javascript.js
> +               var inp = program = document.getElementById("t1").value;
Надо сканировать на правильность скобок `sentence`, а не `document.getElementById("t1").value`.

2022-09-17 13:12 UTC, Mazdaywik commented on js/javascript.js
> +         if (n == 1) {
И здесь отступ поехал, поправьте, пожалуйста.

2022-09-17 13:12 UTC, Mazdaywik commented on js/javascript.js
> +                     }
Круглые и угловые скобки нужно проверять одновременно, а не по очереди. Если проверять по очереди, то в ошибочном выражении `a(b<c)d>e` ошибка не обнаружится. А она есть — скобки идут внахлёст.

2022-09-17 13:12 UTC, Mazdaywik commented on js/javascript.js
> +                  string1.replaceAll('()', '');}
Замену нужно выполнять в цикле:
`'((()))'` → `'(())'` → `'()'` → `''`

2022-09-18 07:27 UTC, MiNombreEsPetros commented on js/javascript.js
> +                  string1.replaceAll('()', '');}
for(let o1 = 0; o1<string1.length;o1++){ - а это не цикл?

2022-09-18 07:28 UTC, Mazdaywik commented on js/javascript.js
> +                  string1.replaceAll('()', '');}
Тогда отступ надо поправить, чтобы цикл был очевиден.

2022-09-18 07:29 UTC, MiNombreEsPetros commented on js/javascript.js
> +                     }
А здесь мне видимо нужна будет Ваша помощь

2022-09-18 07:30 UTC, MiNombreEsPetros commented on js/javascript.js
> +                  string.replaceAll('()', '');}
А что означает отступ поехал?

2022-09-18 10:04 UTC, Mazdaywik commented on js/javascript.js
> +                  string.replaceAll('()', '');}
Это означает, что должно быть написано вот так:
```javascript
                  string = a.join("");
                  for(let o = 0; o<string.length;o++){
                        string.replaceAll('()', '');
                  }
```
Т.е. строчка кода, которая находится внутри цикла, должна быть написана с отступом относительно заголовка цикла.

2022-09-18 10:11 UTC, Mazdaywik commented on js/javascript.js
> +                  string.replaceAll('()', '');}
Можно зайти на сайт <https://beautifier.io/>, скопировать в него всю функцию `checkSentence()`, выбрать в настройках слева «Indent with 3 spaces» и нажать большую зелёную кнопку «Beautify Code _(Ctrl-Enter)_». Далее вставить код и закоммитить — с отступами проблем не будет.

2022-09-18 10:16 UTC, Mazdaywik commented on js/javascript.js
> +                     }
```javascript
                  var b = [];
                  for (let p = 0; p < missionname.length; p++) {
                     if (missionname[p] == "(" || missionname[p] == ")"
                            || missionname[p] == "<" || missionname[p] == ">") {
                        b.push(missionname[p]);
                     }
                  }
                  string1 = b.join("");
                  for (let o1 = 0; o1 < string1.length; o1++) {
                     string1 = string1.replaceAll('()', '');
                     string1 = string1.replaceAll('<>', '');
                  }
```
Остальное как у Вас написано.

Кстати, `.replaceAll()` не меняет строку, а создаёт новую, поэтому нужно писать вот так:
```javascript
                     // ✔ правильно
                     string1 = string1.replaceAll('()', '');
                     // ❌ неправильно
                     string1.replaceAll('()', '');
```

2022-09-19 04:29 UTC, Mazdaywik requested changes
Уже лучше.

2022-09-19 04:29 UTC, Mazdaywik commented on js/javascript.js
> +         tokens[tokens.length] = '=';
Здесь не нужно исправлять, здесь всё правильно было.

2022-09-19 04:29 UTC, Mazdaywik commented on js/javascript.js
> +      var missionname = result[1];
Не будет работать, если пользователь по ошибке вообще не напишет знак `'='` в предложении. Разбивать предложение на части нужно после того, как мы убедились, что токен `'=='` у нас есть и он один (после цикла, если `n == 1`).

2022-09-19 04:29 UTC, Mazdaywik commented on js/javascript.js
> +      var result = sentence.toString().split('=');
Так разбивать неправильно. Нужно в массиве найти токен `'=='`:
```javascript
var eq_pos = sentence.indexOf('==');
```
а затем по нему разбить массив:
```javascript
var rocketname = sentence.slice(0, eq_pos);
var missionname = sentence.slice(eq_pos + 1);
```

2023-12-04 12:45 UTC, Mazdaywik commented
Не актуален

2023-12-04 12:45 UTC, closed without merging