Реализация полного интерпретатора tiny-refal.
bmstu-iu9/tiny-refal pull request #12
Opened 2024-02-15 08:35 UTC by MainframeKnight

2024-02-27 09:55 UTC, Mazdaywik requested changes
Поместитие в первый коммит удаление старой реализации, во второй коммит — весь новый код. Главный файл должен называться `index.html`.

2024-02-27 09:55 UTC, Mazdaywik commented on README.md
> +* именованных функций — программа - это просто набор предложений,
Длинное тире

2024-02-27 09:55 UTC, Mazdaywik commented on highlighter.js
> +                } else if ((text_str[i][j] == "e" || text_str[i][j] == "s" || text_str[i][j] == "t") && j != text_str[i].length - 1 && RegExp("[0-9a-zA-Z]").test(text_str[i][j + 1])) {
Длинные строки ограничте 120 символами.

2024-02-27 09:55 UTC, Mazdaywik commented on highlighter.js
> +        // }
Закомментированный код — мусор, подлежащий удалению.

2024-02-27 16:32 UTC, Mazdaywik commented
А почему правки `README.md` находятся в коммите «Удаление старых файлов»?

2024-02-27 16:33 UTC, Mazdaywik requested changes
А почему правки `README.md` находятся в «Удалении старых файлов»?

2024-05-17 10:26 UTC, MainframeKnight commented
Здравствуйте, Александр Владимирович! Посмотрите, пожалуйста, мою ветку!

2024-05-29 04:41 UTC, Mazdaywik requested changes
В первом коммите старый `README.md` удалять не надо было.

2024-05-29 04:41 UTC, Mazdaywik commented on README.md
> +
Неразрывные пробелы в `README.md` я сам потом добавлю.

2024-05-29 04:41 UTC, Mazdaywik commented on highlighter.js
> +                    j += '<span style="color: rgb(255, 94, 20)">(</span>'.length - 1;
Повторяющиеся строчки вроде `'<span style="color: rgb(255, 94, 20)">(</span>'` вынесите в именованные константы.

2024-05-29 04:41 UTC, Mazdaywik commented on lexer.js
> +                    document.querySelector("#result_field").innerHTML = `Ошибка: пустые скобки активации: ${str}.`;
Нет такой ошибки.

2024-05-29 04:41 UTC, Mazdaywik commented on index.html
> +<head>
Где тег `<html>`?

2024-05-29 07:50 UTC, MainframeKnight commented on highlighter.js
> +                    j += '<span style="color: rgb(255, 94, 20)">(</span>'.length - 1;
Дублирование кода устранено с помощью введения порождающей повторяющиеся строки функции colorWrapper (аргументы: color - цвет выделения, content - выделяемая цветом строка).

2024-05-29 07:50 UTC, MainframeKnight commented on lexer.js
> +                    document.querySelector("#result_field").innerHTML = `Ошибка: пустые скобки активации: ${str}.`;
Исправлено.

2024-05-29 07:51 UTC, MainframeKnight commented on index.html
> +<head>
В файле присутствовал тег html на 1-й строке, но он не был закрыт в конце файла. Исправлено.

2024-05-29 07:52 UTC, MainframeKnight commented
Исправления выполнены. Можете, пожалуйста, посмотреть мою ветку?

2024-05-29 08:08 UTC, Mazdaywik requested changes
Верните файл `README.md` в первый коммит.

2024-05-29 08:08 UTC, Mazdaywik commented on highlighter.js
> +                    j += colorWrapper("255, 94, 20", ')').length - 1;
Повторяющиеся строчки вроде `colorWrapper("255, 94, 20", ')')` вынесите в именованные константы:
```javascript
const CLOSE_BRACKET_FORMATTED = colorWrapper("255, 94, 20", ')');
```

2024-05-29 08:08 UTC, Mazdaywik commented on index.html
> +<head>
Вообще-то в первой строке тег `DOCTYPE`, тега `<html>` нету.

2024-05-29 08:44 UTC, MainframeKnight commented on highlighter.js
> +                    j += colorWrapper("255, 94, 20", ')').length - 1;
Исправлено.

2024-05-29 08:45 UTC, MainframeKnight commented on index.html
> +<head>
Я думал, что !DOCTYPE html и html эквивалентны. Исправил.

2024-05-29 09:09 UTC, MainframeKnight commented
Исправления выполнены. Можете, пожалуйста, посмотреть мою ветку?

2024-05-29 18:30 UTC, Mazdaywik requested changes

2024-05-29 18:30 UTC, Mazdaywik commented on index.html
> +<head>
Добавьте отступ для кода внутри `<html>…</html>`.

2024-05-29 18:48 UTC, Mazdaywik requested changes
Лексический анализатор и раскраска кода не соответствуют спецификации, описанной здесь:

https://github.com/bmstu-iu9/tiny-refal/issues/5#issue-1305880752

* Пробелы игнорируются везде. Т.е. строка `set is set` описывает 4 переменные `se`, `ti`, `ss`, `et`, не смотря на то, что между типом и индексом стоит знак пробела.
* Вторым символом после знака `\` в поле программы может быть только `\`, `s`, `t`, `e`, `#`, `=`, остальное — ошибка. В поле зрения допустимы только две escape-последовательности — `\\` и `\#`. (Да, в спецификации я забыл, что `\` тоже надо экранировать.)
* Имя переменной состоит из одного символа (можно его ограничить буквой или цифрой, можно и не ограничивать, допуская переменные вида `s🤪`). Кстати, в раскраске индексы переменных лучше отображать как индексы: `s<sub>X</sub>` — такова, на самом деле, была исходная задумка. Если пользователь по ошибке напишет пробелы между типом переменной и индексом, во время раскраски их можно удалять: `s X` → <tt>s<sub>X</sub></tt> (или `e   😎` → <tt>e<sub>😎</sub></tt>.

Токенизацию и раскраску можно делать одновременно, кстати. Чтобы не делать дважды одну работу.

P.S. Сразу после закрытия этого запроса на слияние будет одна простая заявка (issue) — вы должны познакомиться и с этим механизмом.

2024-05-30 18:04 UTC, MainframeKnight commented on index.html
> +<head>
Отступы добавлены.

2024-05-30 18:06 UTC, MainframeKnight commented
Исправления выполнены. Можете, пожалуйста, посмотреть мою ветку?

2024-05-31 07:41 UTC, Mazdaywik approved these changes

2024-05-31 07:41 UTC, Mazdaywik commented
А сейчас будет заявка…

2024-05-31 14:26 UTC, merged