Базовый дизайн
bmstu-iu9/tiny-refal pull request #2
Opened 2022-07-11 22:30 UTC by MiNombreEsPetros

2022-07-12 07:51 UTC, MiNombreEsPetros commented
Основной коммит это basic user interface 
Все остальные не считаются

2022-07-13 10:50 UTC, Mazdaywik requested changes
* [ ] Всю эту кучу коммитов нужно слить в один, в истории такая шелуха не нужна.
* [ ] Интерфейс должен быть на русском.
* [ ] Выбор урока и примера должен быть не снизу, а сверху.

2022-07-13 10:50 UTC, Mazdaywik commented on css/style.css
> +}
Добавьте перевод строки в конец, чтобы не отображался ![image](https://user-images.githubusercontent.com/1309859/178716029-02339881-edf5-4d5d-b690-0c030f2611b5.png)

2022-07-13 10:50 UTC, Mazdaywik commented on index.html
> +
Куча пустых строк.

2022-07-13 10:50 UTC, Mazdaywik commented on index.html
> +         <option value="Lesson 4">Lesson 4</option>
Списки уроков и примеров должны формироваться после чтения файла. Пока оставить можно, но потом надо переделать.

2022-07-13 10:50 UTC, Mazdaywik commented on js/javascript.js
> +window.onload = textchange5;
Добавьте перевод строки, чтобы исчез ![image](https://user-images.githubusercontent.com/1309859/178716383-b6d0f480-1284-4fbf-a700-4dee844e3c9f.png)

2022-07-13 10:50 UTC, Mazdaywik commented on index.html
> +</html>
Добавьте перевод строки, чтобы исчез ![image](https://user-images.githubusercontent.com/1309859/178716545-d18d9f82-d85c-4b63-9ada-358e06975add.png)

2022-07-13 10:57 UTC, Mazdaywik commented
Как слить коммиты:
```
git reset --soft main
git commit -m "Базовый дизайн"
git push -f
```

2022-07-13 11:27 UTC, closed without merging